function convert(text, text2)
{
  var converted_text="";

  for (i=0;i<text.value.length;i++)
  {
    if(tableau[text.value.charAt(i)]!=undefined)
    {
      converted_text+=tableau[text.value.charAt(i)];
    }
    else{converted_text+=text.value.charAt(i);}
  }
  text2.value=converted_text;
}

function genarray()
{
tableau= new Array(); /* tableau global */
tableau["€"]= "&euro;" ;
tableau["�"]= "&#129;" ;
tableau["‚"]= "&#130;" ;
tableau["ƒ"]= "&#131;" ;
tableau["„"]= "&#132;" ;
tableau["…"]= "&#133;" ;
tableau["†"]= "&#134;" ;
tableau["‡"]= "&#135;" ;
tableau["ˆ"]= "&#136;" ;
tableau["‰"]= "&#137;" ;
tableau["Š"]= "&#138;" ;
tableau["‹"]= "&lt;" ;
tableau["Œ"]= "&#140;" ;
tableau["�"]= "&#141;" ;
tableau["Ž"]= "&#142;" ;
tableau["�"]= "&#143;" ;
tableau["�"]= "&#144;" ;
tableau["‘"]= "'" ;
tableau["’"]= "'" ;
tableau["“"]= "&#147;" ;
tableau["”"]= "&#148;" ;
tableau["•"]= "&#149;" ;
tableau["–"]= "&#150;" ;
tableau["—"]= "&#151;" ;
tableau["˜"]= "&#152;" ;
tableau["™"]= "&#153;" ;
tableau["š"]= "&#154;" ;
tableau["›"]= "&gt;" ;
tableau["œ"]= "&oelig;" ;
tableau["�"]= "&#157;" ;
tableau["ž"]= "&#158;" ;
tableau["Ÿ"]= "&Yuml;" ;
tableau["espace"]= "&nbsp;" ;
tableau["¡"]= "&iexcl;" ;
tableau["¢"]= "&cent;" ;
tableau["£"]= "&pound;" ;
tableau["¤"]= "&curren;" ;
tableau["¥"]= "&yen" ;
tableau["¦"]= "&brvbar;" ;
tableau["§"]= "&sect;" ;
tableau["¨"]= "&uml;" ;
tableau["©"]= "&copy;   " ;
tableau["ª"]= "&ordf;" ;
tableau["«"]= "&laquo;" ;
tableau["¬"]= "&not;" ;
tableau["­"]= "&shy;" ;
tableau["®"]= "&reg;" ;
tableau["¯"]= "&masr;" ;
tableau["°"]= "&deg;" ;
tableau["±"]= "&plusmn;" ;
tableau["²"]= "&sup2;" ;
tableau["³"]= "&sup3;" ;
tableau["´"]= "&acute;" ;
tableau["µ"]= "&micro;" ;
tableau["¶"]= "&para;" ;
tableau["·"]= "&middot;" ;
tableau["¸"]= "&cedil;" ;
tableau["¹"]= "&sup1;" ;
tableau["º"]= "&ordm;" ;
tableau["»"]= "&raquo;" ;
tableau["¼"]= "&frac14;" ;
tableau["½"]= "&frac12;" ;
tableau["¾"]= "&frac34;" ;
tableau["¿"]= "&iquest;" ;
tableau["À"]= "&Agrave;" ;
tableau["Á"]= "&Aacute;" ;
tableau["Â"]= "&Acirc;" ;
tableau["Ã"]= "&Atilde;" ;
tableau["Ä"]= "&Auml;" ;
tableau["Å"]= "&Aring;" ;
tableau["Æ"]= "&Aelig" ;
tableau["Ç"]= "&Ccedil;" ;
tableau["È"]= "&Egrave;" ;
tableau["É"]= "&Eacute;" ;
tableau["Ê"]= "&Ecirc;" ;
tableau["Ë"]= "&Euml;" ;
tableau["Ì"]= "&Igrave;" ;
tableau["Í"]= "&Iacute;" ;
tableau["Î"]= "&Icirc;" ;
tableau["Ï"]= "&Iuml;" ;
tableau["Ð"]= "&eth;" ;
tableau["Ñ"]= "&Ntilde;" ;
tableau["Ò"]= "&Ograve;" ;
tableau["Ó"]= "&Oacute;" ;
tableau["Ô"]= "&Ocirc;" ;
tableau["Õ"]= "&Otilde;" ;
tableau["Ö"]= "&Ouml;" ;
tableau["×"]= "&times;" ;
tableau["Ø"]= "&Oslash;" ;
tableau["Ù"]= "&Ugrave;" ;
tableau["Ú"]= "&Uacute;" ;
tableau["Û"]= "&Ucirc;" ;
tableau["Ü"]= "&Uuml;" ;
tableau["Ý"]= "&Yacute;" ;
tableau["Þ"]= "&thorn;" ;
tableau["ß"]= "&szlig;" ;
tableau["à"]= "&agrave;" ;
tableau["á"]= "&aacute;" ;
tableau["â"]= "&acirc;" ;
tableau["ã"]= "&atilde;" ;
tableau["ä"]= "&auml;" ;
tableau["å"]= "&aring;" ;
tableau["æ"]= "&aelig;" ;
tableau["ç"]= "&ccedil;" ;
tableau["è"]= "&egrave;" ;
tableau["é"]= "&eacute;" ;
tableau["ê"]= "&ecirc;" ;
tableau["ë"]= "&euml;" ;
tableau["ì"]= "&igrave;" ;
tableau["í"]= "&iacute;" ;
tableau["î"]= "&icirc;" ;
tableau["ï"]= "&iuml;" ;
tableau["ð"]= "&eth;" ;
tableau["ñ"]= "&ntilde;" ;
tableau["ò"]= "&ograve;" ;
tableau["ó"]= "&oacute;" ;
tableau["ô"]= "&ocirc;" ;
tableau["õ"]= "&otilde;" ;
tableau["ö"]= "&ouml;" ;
tableau["÷"]= "&divide;" ;
tableau["ø"]= "&oslash;" ;
tableau["ù"]= "&ugrave;" ;
tableau["ú"]= "&uacute;" ;
tableau["û"]= "&ucirc;" ;
tableau["ü"]= "&uuml;" ;
tableau["ý"]= "&yacute;" ;
tableau["þ"]= "&thorn;" ;
tableau["ÿ"]= "&yuml;" ;

}